# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49a1d00f554884557083c7dd605573e72d6ebe302f440239b4061722a0ba30d51f771e3ded2b4a8fb4700f43a5946373269aa801fb428891634f9bf8d9e34ae

test:
  secret_key_base: 6b4de2bacd4e0f0ef58af19b3197bc30f25bb41255995cde40480249d37e0c01fff4d1d821011f13c1e1eb2bb8c15049dd25c4bce74f620d9404ff479ffd615f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
